logging:
  level:
    org:
      hibernate: ERROR
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/vmodemo?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC&useSSL=false&createDatabaseIfNotExist=true
    password: ''
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: '8081'

